FROM golang:1.18.4-alpine3.16

WORKDIR /src/go

COPY . .

ENV CGO_ENABLED=0

RUN go install github.com/swaggo/swag/cmd/swag@latest
RUN go install golang.org/x/tools/cmd/godoc@latest
RUN go install github.com/cucumber/godog/cmd/godog@latest

RUN swag init
RUN go mod tidy

CMD [ "godog", "run", "./features/." ]
