#!/bin/bash
HELPERS="e2e_api_client"

if [ ! -e ".env.test.local" ]; then
	cp .env.test.example .env.test.local
fi

for CONTAINER in $HELPERS; do
	docker-compose -f docker-compose.e2e.yml up -d --build $CONTAINER
done

docker-compose -f docker-compose.e2e.yml up --build e2e_api_test_runner
EXIT_CODE=$(docker inspect -f '{{.State.ExitCode}}' e2e_api_test_runner)

docker-compose -f docker-compose.e2e.yml down

exit $EXIT_CODE
