#!/bin/bash
HELPERS="e2e_api_client"
HOSTNAME=$(hostname)

if [ ! -e ".env.test.local" ]; then
	cp .env.test.example .env.test.local
fi

for CONTAINER in $HELPERS; do
	if [[ "${HOSTNAME}" == "nave-jean" ]]; then
		docker-compose -f docker-compose.e2e.yml up -d $CONTAINER
	else
		docker-compose -f docker-compose.e2e.yml up -d --build --force-recreate $CONTAINER
	fi
done

if [[ "${HOSTNAME}" == "nave-jean" ]]; then
	docker-compose -f docker-compose.e2e.yml up e2e_api_test_runner
else
	docker-compose -f docker-compose.e2e.yml up --build --force-recreate e2e_api_test_runner
fi

EXIT_CODE=$(docker inspect -f '{{.State.ExitCode}}' e2e_api_test_runner)

docker-compose -f docker-compose.e2e.tyml logs -f e2e_api_client

docker-compose -f docker-compose.e2e.yml down

exit $EXIT_CODE
