#!/bin/bash

DOCKERIZE_VERSION=v0.6.1
wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz

# tar -C /usr/local/bin -xzvf dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz

if [ ! -e ".docker/dockerize" ]; then
	mkdir -p .docker/dockerize
	tar -C .docker/dockerize -xzvf dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz
fi

rm dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz

