// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	handler "github.com/jeanmolossi/effective-eureka/src/core/modules/handler"
	input "github.com/jeanmolossi/effective-eureka/src/core/modules/input"

	mock "github.com/stretchr/testify/mock"
)

// CreateModule is an autogenerated mock type for the CreateModule type
type CreateModule struct {
	mock.Mock
}

// Input provides a mock function with given fields:
func (_m *CreateModule) Input() *input.CreateModule {
	ret := _m.Called()

	var r0 *input.CreateModule
	if rf, ok := ret.Get(0).(func() *input.CreateModule); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*input.CreateModule)
		}
	}

	return r0
}

// Run provides a mock function with given fields:
func (_m *CreateModule) Run() (*handler.HttpModuleCreated, error) {
	ret := _m.Called()

	var r0 *handler.HttpModuleCreated
	if rf, ok := ret.Get(0).(func() *handler.HttpModuleCreated); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*handler.HttpModuleCreated)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
