// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	domain "github.com/jeanmolossi/effective-eureka/src/core/courses/domain"
	mock "github.com/stretchr/testify/mock"
)

// EditCourseInfo is an autogenerated mock type for the EditCourseInfo type
type EditCourseInfo struct {
	mock.Mock
}

// Run provides a mock function with given fields: course
func (_m *EditCourseInfo) Run(course domain.Course) (domain.Course, error) {
	ret := _m.Called(course)

	var r0 domain.Course
	if rf, ok := ret.Get(0).(func(domain.Course) domain.Course); ok {
		r0 = rf(course)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.Course)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(domain.Course) error); ok {
		r1 = rf(course)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
