// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	domain "github.com/jeanmolossi/effective-eureka/src/core/sections/domain"
	mock "github.com/stretchr/testify/mock"
)

// EditSectionInfo is an autogenerated mock type for the EditSectionInfo type
type EditSectionInfo struct {
	mock.Mock
}

// Run provides a mock function with given fields: section
func (_m *EditSectionInfo) Run(section domain.Section) (domain.Section, error) {
	ret := _m.Called(section)

	var r0 domain.Section
	if rf, ok := ret.Get(0).(func(domain.Section) domain.Section); ok {
		r0 = rf(section)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.Section)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(domain.Section) error); ok {
		r1 = rf(section)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
