// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	domain "github.com/jeanmolossi/effective-eureka/src/core/courses/domain"
	mock "github.com/stretchr/testify/mock"
)

// GetCoursesFromStudent is an autogenerated mock type for the GetCoursesFromStudent type
type GetCoursesFromStudent struct {
	mock.Mock
}

// Run provides a mock function with given fields: studentID
func (_m *GetCoursesFromStudent) Run(studentID string) ([]domain.Course, error) {
	ret := _m.Called(studentID)

	var r0 []domain.Course
	if rf, ok := ret.Get(0).(func(string) []domain.Course); ok {
		r0 = rf(studentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Course)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(studentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
