// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	domain "github.com/jeanmolossi/effective-eureka/src/core/courses/domain"
	mock "github.com/stretchr/testify/mock"
)

// GetCourses is an autogenerated mock type for the GetCourses type
type GetCourses struct {
	mock.Mock
}

// Run provides a mock function with given fields: conditions
func (_m *GetCourses) Run(conditions *domain.GetCoursesParams) ([]domain.Course, error) {
	ret := _m.Called(conditions)

	var r0 []domain.Course
	if rf, ok := ret.Get(0).(func(*domain.GetCoursesParams) []domain.Course); ok {
		r0 = rf(conditions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Course)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*domain.GetCoursesParams) error); ok {
		r1 = rf(conditions)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
