// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	domain "github.com/jeanmolossi/effective-eureka/src/core/lessons/domain"
	mock "github.com/stretchr/testify/mock"
)

// GetLessonsInSection is an autogenerated mock type for the GetLessonsInSection type
type GetLessonsInSection struct {
	mock.Mock
}

// Run provides a mock function with given fields: sectionID
func (_m *GetLessonsInSection) Run(sectionID string) ([]domain.Lesson, error) {
	ret := _m.Called(sectionID)

	var r0 []domain.Lesson
	if rf, ok := ret.Get(0).(func(string) []domain.Lesson); ok {
		r0 = rf(sectionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Lesson)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(sectionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
