// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	domain "github.com/jeanmolossi/effective-eureka/src/core/modules/domain"
	mock "github.com/stretchr/testify/mock"
)

// GetModuleFromCourse is an autogenerated mock type for the GetModuleFromCourse type
type GetModuleFromCourse struct {
	mock.Mock
}

// Run provides a mock function with given fields: input
func (_m *GetModuleFromCourse) Run(input *domain.GetModulesParams) ([]domain.Module, error) {
	ret := _m.Called(input)

	var r0 []domain.Module
	if rf, ok := ret.Get(0).(func(*domain.GetModulesParams) []domain.Module); ok {
		r0 = rf(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Module)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*domain.GetModulesParams) error); ok {
		r1 = rf(input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
