// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	domain "github.com/jeanmolossi/effective-eureka/src/core/modules/domain"
	mock "github.com/stretchr/testify/mock"
)

// GetModuleByID is an autogenerated mock type for the GetModuleByID type
type GetModuleByID struct {
	mock.Mock
}

// Run provides a mock function with given fields: moduleID
func (_m *GetModuleByID) Run(moduleID string) (domain.Module, error) {
	ret := _m.Called(moduleID)

	var r0 domain.Module
	if rf, ok := ret.Get(0).(func(string) domain.Module); ok {
		r0 = rf(moduleID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.Module)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(moduleID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
