// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	domain "github.com/jeanmolossi/effective-eureka/src/core/purchases/domain"
	mock "github.com/stretchr/testify/mock"
)

// GetPurchases is an autogenerated mock type for the GetPurchases type
type GetPurchases struct {
	mock.Mock
}

// Get provides a mock function with given fields: email, transaction
func (_m *GetPurchases) Get(email string, transaction string) ([]domain.Item, error) {
	ret := _m.Called(email, transaction)

	var r0 []domain.Item
	if rf, ok := ret.Get(0).(func(string, string) []domain.Item); ok {
		r0 = rf(email, transaction)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Item)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(email, transaction)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
