// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// GetSectionLessons is an autogenerated mock type for the GetSectionLessons type
type GetSectionLessons struct {
	mock.Mock
}

// Run provides a mock function with given fields: sectionID
func (_m *GetSectionLessons) Run(sectionID string) ([]interface{}, error) {
	ret := _m.Called(sectionID)

	var r0 []interface{}
	if rf, ok := ret.Get(0).(func(string) []interface{}); ok {
		r0 = rf(sectionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(sectionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
