// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ModuleErrorMap is an autogenerated mock type for the ModuleErrorMap type
type ModuleErrorMap struct {
	mock.Mock
}

// GetErrorMap provides a mock function with given fields:
func (_m *ModuleErrorMap) GetErrorMap() map[string]map[string]error {
	ret := _m.Called()

	var r0 map[string]map[string]error
	if rf, ok := ret.Get(0).(func() map[string]map[string]error); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]map[string]error)
		}
	}

	return r0
}
