// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	domain "github.com/jeanmolossi/effective-eureka/src/core/purchases/domain"
	factory "github.com/jeanmolossi/effective-eureka/src/core/purchases/factory"

	mock "github.com/stretchr/testify/mock"
)

// Product is an autogenerated mock type for the Product type
type Product struct {
	mock.Mock
}

// Build provides a mock function with given fields:
func (_m *Product) Build() (domain.Product, error) {
	ret := _m.Called()

	var r0 domain.Product
	if rf, ok := ret.Get(0).(func() domain.Product); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.Product)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: product
func (_m *Product) Create(product map[string]interface{}) factory.Product {
	ret := _m.Called(product)

	var r0 factory.Product
	if rf, ok := ret.Get(0).(func(map[string]interface{}) factory.Product); ok {
		r0 = rf(product)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(factory.Product)
		}
	}

	return r0
}
