// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	domain "github.com/jeanmolossi/effective-eureka/src/core/students/domain"
	mock "github.com/stretchr/testify/mock"
)

// RegisterStudent is an autogenerated mock type for the RegisterStudent type
type RegisterStudent struct {
	mock.Mock
}

// Run provides a mock function with given fields: student
func (_m *RegisterStudent) Run(student domain.Student) (domain.Student, error) {
	ret := _m.Called(student)

	var r0 domain.Student
	if rf, ok := ret.Get(0).(func(domain.Student) domain.Student); ok {
		r0 = rf(student)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.Student)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(domain.Student) error); ok {
		r1 = rf(student)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
