definitions:
  handler.HttpCourseCreated:
    properties:
      course_id:
        example: 05d4d9d3-01a3-4fd3-8d3e-e3178522f514
        type: string
      course_published:
        example: false
        type: boolean
    type: object
  handler.HttpCreateCourseBadRequestErr:
    properties:
      error:
        example: Bad Request
        type: string
      errors:
        items:
          $ref: '#/definitions/shared.FieldError'
        type: array
    type: object
  httputil.HttpInternalServerErr:
    properties:
      error:
        example: internal server error
        type: string
    type: object
  httputil.PingInternalServerErr:
    properties:
      message:
        example: unexpected error
        type: string
    type: object
  httputil.PingOk:
    properties:
      message:
        example: pong
        type: string
    type: object
  input.CreateCourse:
    properties:
      description:
        example: This is a catalog video manager API.
        maxLength: 255
        type: string
      published:
        example: true
        type: boolean
      thumbnail:
        example: https://effective-eureka.s3.amazonaws.com/courses/thumbnail/1.jpg
        type: string
      title:
        example: Effective Eureka
        maxLength: 255
        type: string
    required:
    - title
    type: object
  shared.FieldError:
    properties:
      field:
        example: title
        type: string
      message:
        example: title is required
        type: string
    type: object
info:
  contact: {}
paths:
  /course:
    post:
      consumes:
      - application/json
      description: Create a course
      parameters:
      - description: Course object which will be created
        in: body
        name: course
        required: true
        schema:
          $ref: '#/definitions/input.CreateCourse'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handler.HttpCourseCreated'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.HttpCreateCourseBadRequestErr'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HttpInternalServerErr'
      summary: Course creation
      tags:
      - courses
  /ping:
    get:
      consumes:
      - application/json
      description: A simple health check.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/httputil.PingOk'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.PingInternalServerErr'
        "502":
          description: Bad Gateway
          schema:
            $ref: '#/definitions/httputil.PingInternalServerErr'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/httputil.PingInternalServerErr'
      summary: Ping the server.
      tags:
      - healthcheck
swagger: "2.0"
