definitions:
  httputil.PingInternalServerErr:
    properties:
      message:
        example: unexpected error
        type: string
    type: object
  httputil.PingOk:
    properties:
      message:
        example: pong
        type: string
    type: object
  input.CreateCourse:
    properties:
      description:
        example: This is a catalog video manager API.
        maxLength: 255
        type: string
      published:
        example: true
        type: boolean
      thumbnail:
        example: https://effective-eureka.s3.amazonaws.com/courses/thumbnail/1.jpg
        type: string
      title:
        example: Effective Eureka
        maxLength: 255
        type: string
    required:
    - title
    type: object
info:
  contact: {}
paths:
  /courses:
    post:
      consumes:
      - application/json
      description: Create a course
      parameters:
      - description: Course object which will be created
        in: body
        name: course
        required: true
        schema:
          $ref: '#/definitions/input.CreateCourse'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema: {}
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.PingInternalServerErr'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.PingInternalServerErr'
      summary: Course creation
      tags:
      - courses
  /ping:
    get:
      consumes:
      - application/json
      description: A simple health check.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/httputil.PingOk'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.PingInternalServerErr'
        "502":
          description: Bad Gateway
          schema:
            $ref: '#/definitions/httputil.PingInternalServerErr'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/httputil.PingInternalServerErr'
      summary: Ping the server.
      tags:
      - healthcheck
swagger: "2.0"
