name: Run tests

on:
    push:
        branches: [ "main", "develop" ]
    pull_request:
        branches: [ "main" ]

jobs:
    test:
        runs-on: ubuntu-22.04

        steps:
        - uses: actions/checkout@v3

        - name: unit
          run: make test

    e2e-test:
        runs-on: ubuntu-22.04

        steps:
        - uses: actions/checkout@v3

        - name: e2e-test
          run: make e2e-test
